### ISSUE TITLE
Tried on several sites and it does not work

### ISSUE THREAD

**Issue by D64134n0** [doggy8088/AvoidClosingTab#1]
I can see the tampermonky icon with the red 1 meaning 1 script is running on the site. This one ovbiously.
I close the tab or the browser and no warning at all. The tab or browser just closes as usual.
If you need more details do not hesitate to contact me.

**Comment by doggy8088** [comment]
Can you provide a link for me to test your scenario?

**Comment by D64134n0** [comment]
Here is a short video of my test.
https://1drv.ms/v/s!Akle7beiDth4kPQ6vdc5pGvETqLMxQ?e=j8Y21G
I used this same page and another to test. First time worked and then it stopped working.

**Comment by doggy8088** [comment]
My script originally only supported two websites: `https://*.github.dev/*` and `https://*.scm.azurewebsites.net/dev/*`. That's why it's not working on OneDrive site.

I released version 0.2. You can take a try. It apply to all sites by default now.

By the way, OneDrive has its own implementation. So only after you play on the video, the extension should work.

**Comment by D64134n0** [comment]
Thank you for your efforts, Will. People like you who take the time to do things, big or small, for free for the benefit of all, make humanity move forward. 
My problem was really solved by switching from Chrome and start using workspaces+groups in Edge. It is like groups within groups and with the tab lock feature I always keep my work environment the same.
